### ISSUE TITLE
Unzip the buster

### ISSUE THREAD

**Issue by myildirimm** [2e0byo/YADC#15]
I have download buster and show the files path but got error.

YADC-master\yadc\browser.py", line 239, in validate_buster
    raise BrowserError("Please unzip buster and pass the dir.")
yadc.browser.BrowserError: Please unzip buster and pass the dir.

What is the solution to this?
Thanks

**Comment by 2e0byo** [comment]
You're not passing the correct path to the dir holding the unzipped buster.  Check your paths carefully.

**Comment by myildirimm** [comment]
![image](https://user-images.githubusercontent.com/85634147/187195045-da22aa86-eefe-4511-b9c8-728261df4dd1.png)
![image](https://user-images.githubusercontent.com/85634147/187195136-79e73733-52fd-4d0b-84be-e684b9847346.png)

**Comment by myildirimm** [comment]
This is how I did and did not work.

**Comment by 2e0byo** [comment]
Shouldn't your path be `r"C:\Users\my00499\Downloads\YADC-master\buster-1.3.1"`?  (assuming I've made no typos).  YADC expects the dir containing the files you extracted from the zip, not one level higher.

There's no need to (indeed you probably shouldn't) edit the source like you're doing.  Pass the buster path through in your `main.py` (see [the example](https://github.com/2e0byo/YADC/blob/master/main.py#L35)).

Note that if the other bug reports are accurate, YADC no longer works with TOR. Thus you may need to do some work (e.g. using a vpn) to get it going.  Unfortunately I no longer develop it.  Good luck!

**Comment by myildirimm** [comment]
Now I am getting access denied. Is it normal.
![image](https://user-images.githubusercontent.com/85634147/187446794-79d7ff82-0b08-42d9-aa69-23e8c7f762ab.png)

**Comment by 2e0byo** [comment]
Unfortunately I don't use windows; I have no idea why you're getting a permissions error.  YADC is very unlikely to work off-the-shelf in any case with the latest anti-bot protections, and I'm pretty certain TOR won't work at all.  If you're interested in coding the next iteration of scraper it's probably a good start.  If you just need a test (because the waiting times are still ridiculous) you may sadly be better off with a paid service (I have no experience with them).

I'll add a proper notice to the front page that this repository is not actively supported.

**Comment by myildirimm** [comment]
Thanks a lot for your help and support.
