### ISSUE TITLE
TypeError: unsupported operand type

### ISSUE THREAD

**Issue by chrishat34** [2e0byo/YADC#8]
![error-2022-02-21_19-37-15](https://user-images.githubusercontent.com/43535243/155023617-de909955-88f1-4318-841a-557504d978fe.png)
[error-2022-02-21_19-37-15.txt](https://github.com/2e0byo/YADC/files/8111965/error-2022-02-21_19-37-15.txt)

**Comment by 2e0byo** [comment]
oops. Should be `elapsed.seconds`.  Will fix.

**Comment by chrishat34** [comment]
as this:
subtract = elapsed.seconds if elapsed else 0
        #jch added .seconds
        return max(self.period * 60 - elapsed.seconds, 0)

**Comment by 2e0byo** [comment]
Yes exactly.  Madly busy atm: if you PR that I'll merge it.  Otherwise I'll get at the codebase in a few days.  This is where YADC suffers from the lack of a decent testsuite: that's the kind of typo which really should be been caught earlier...

**Comment by 2e0byo** [comment]
Note that I was not quite right:

```python
        subtract = elapsed.seconds if elapsed else 0
        return max(self.period * 60 - subtract, 0)
```

The first line works out how much to subtract to take into account the runtime of the last run, ignoring `elapsed` if it wasn't passed (it's optional); the second returns how many seconds to sleep to make up the required time, capping the duration at zero since we can't go back in time if the run took longer than it should have.

The solution above (`elapsed.seconds`) will fail if elapsed is not passed.  I believe all the code in this repo actually does pass it, so the issue is trivial.

**Comment by chrishat34** [comment]
nice one - thank you
